version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
    - gci
  settings:
    gci:
      custom-order: true
      sections:
        - standard
        - prefix(github.com/onsi)
        - default
        - prefix(github.com/inference-gateway/)
        - prefix(github.com/inference-gateway/operator)
  exclusions:
    generated: lax

linters:
  default: none
  enable:
    - dupl
    - errcheck
    - copyloopvar
    - ginkgolinter
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused

  settings:
    revive:
      rules:
        - name: comment-spacings
    lll:
      line-length: 250
