# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
---
version: 2

project_name: operator

before:
  hooks:
    - go mod tidy

builds:
  - id: operator
    main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - "v1"
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser -X main.treeState={{ .IsGitDirty }}

dockers_v2:
  - id: operator
    ids:
      - operator
    dockerfile: Dockerfile.goreleaser
    images:
      - ghcr.io/inference-gateway/operator
    tags:
      - "{{ .Version }}"
      - "{{ if not (contains .Tag `rc`) }}latest{{ end }}"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: "{{ .Version }}"
    flags:
      - "--pull"

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"

changelog:
  disable: true

release:
  disable: true
