---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: k3d-dev
product: k3d
registry: k3d-registry
k3d:
  v1alpha5Simple:
    servers: 1
    agents: 2
    image: docker.io/rancher/k3s:v1.32.0-k3s1
    options:
      k3s:
        extraArgs:
          - arg: --disable=traefik
            nodeFilters:
              - server:0
