---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: inference-gateway-operator
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: inference-gateway-metrics-service
spec:
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    control-plane: inference-gateway-operator
    app.kubernetes.io/name: operator
