---
apiVersion: core.inference-gateway.com/v1alpha1
kind: Gateway
metadata:
  name: inference-gateway
  namespace: inference-gateway
spec:
  environment: development
  server:
    host: "0.0.0.0"
    port: 8080
  providers:
    - name: DeepSeek
      enabled: true
      env:
        - name: DEEPSEEK_API_KEY
          valueFrom:
            secretKeyRef:
              name: inference-gateway-providers-secret
              key: DEEPSEEK_API_KEY
