---
namespace: inference-gateway-system

namePrefix: operator-

resources:
  - ../../crd
  - ../../rbac
  - ../../operator
  - ../../metrics

images:
  - name: ghcr.io/inference-gateway/operator
    newTag: 0.26.0
