---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: gateway-viewer-role
rules:
  - apiGroups:
      - core.inference-gateway.com
    resources:
      - gateways
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - core.inference-gateway.com
    resources:
      - gateways/status
    verbs:
      - get
