apiVersion: core.inference-gateway.com/v1alpha1
kind: Agent
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: agent-sample
spec:
  image: "ghcr.io/inference-gateway/google-calendar-agent:latest"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  agent:
    llm:
      baseURL: "http://inference-gateway.inference-gateway.svc.cluster.local:8080/v1"
      model: "openai/gpt-4o"
      apiKeySecretRef:
        name: inference-gateway-providers-secret
        key: OPENAI_API_KEY
  mcp:
    enable: true
    servers:
      - "http://mcp-server.inference-gateway.svc.cluster.local:8080"
    endpoint: "/mcp"
    refreshInterval: "5m"
  telemetry:
    enabled: true
    traces:
      exporter:
        otlp:
          endpoint: "http://localhost:4318"
          protocol: "http/protobuf"
    metrics:
      exporter:
        prometheus:
          port: 9464
  env:
    - name: GOOGLE_CALENDAR_MOCK_MODE
      value: "true"
