---
apiVersion: v1
kind: Namespace
metadata:
  name: inference-gateway
  labels:
    inference-gateway.com/managed: "true"
---
apiVersion: core.inference-gateway.com/v1alpha1
kind: Gateway
metadata:
  name: simple-gateway
  namespace: inference-gateway
spec:
  replicas: 1
  image: "ghcr.io/inference-gateway/inference-gateway:latest"
  environment: development
  telemetry:
    enabled: true
    metrics:
      enabled: true
      port: 9464
  server:
    host: "0.0.0.0"
    port: 8080
  providers:
    - name: OpenAI
      env:
        - name: OPENAI_API_URL
          valueFrom:
            configMapKeyRef:
              name: inference-gateway-config
              key: api_url
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: api_key
---
apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
  namespace: inference-gateway
type: Opaque
stringData:
  api_key: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inference-gateway-config
  namespace: inference-gateway
data:
  api_url: "https://api.openai.com/v1"
