---
apiVersion: v1
kind: Namespace
metadata:
  name: mcp
  labels:
    inference-gateway.com/managed: "true"
---
apiVersion: core.inference-gateway.com/v1alpha1
kind: MCP
metadata:
  name: mcp-memory-server
  namespace: mcp
spec:
  image: ghcr.io/inference-gateway/mcp-memory-server:latest
  hpa:
    enabled: true
  server:
    port: 3000
    timeout: "30s"
    tls:
      enabled: true
      secretName: mcp-memory-server-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mcp-tls-cert
  namespace: mcp
spec:
  secretName: mcp-memory-server-tls
  commonName: mcp-memory-server.mcp.svc.cluster.local
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
