---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: allow-metrics-traffic
  namespace: inference-gateway-system
spec:
  podSelector:
    matchLabels:
      control-plane: inference-gateway-operator
      app.kubernetes.io/name: operator
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              metrics: enabled
      ports:
        - port: 8443
          protocol: TCP
