name: E2E Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-e2e:
    name: E2E Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Clone the code
        uses: actions/checkout@v4.2.2

      - name: Setup Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version-file: go.mod

      - name: Install go-task
        run: |
          curl -s https://taskfile.dev/install.sh | sh -s -- -b /usr/local/bin v3.44.1

      - name: Install k3d
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

      - name: Install ctlptl
        run: |
          CTLPTL_VERSION=0.8.40
          curl -fsSL -o /tmp/ctlptl.tar.gz https://github.com/tilt-dev/ctlptl/releases/download/v${CTLPTL_VERSION}/ctlptl.${CTLPTL_VERSION}.linux.x86_64.tar.gz
          tar -xzf /tmp/ctlptl.tar.gz
          sudo mv ctlptl /usr/local/bin/
          sudo chmod +x /usr/local/bin/ctlptl

      - name: Install controller-gen, kustomize, and setup-envtest
        run: |
          CONTROLLER_GEN_VERSION=v0.17.2
          KUSTOMIZE_VERSION=v5.6.0
          ENVTEST_VERSION=latest

          go install sigs.k8s.io/controller-tools/cmd/controller-gen@${CONTROLLER_GEN_VERSION}
          go install sigs.k8s.io/kustomize/kustomize/v5@${KUSTOMIZE_VERSION}
          go install sigs.k8s.io/controller-runtime/tools/setup-envtest@${ENVTEST_VERSION}

          controller-gen --version || (echo "controller-gen not installed" && exit 1)
          kustomize version || (echo "kustomize not installed" && exit 1)
          setup-envtest version || (echo "setup-envtest not installed" && exit 1)

      - name: Setup K8s envtest binaries
        run: |
          ENVTEST_K8S_VERSION=1.32

          mkdir -p bin
          setup-envtest use ${ENVTEST_K8S_VERSION} -p path

      - name: Verify k3d and ctlptl installation
        run: |
          k3d version
          ctlptl version

      - name: Create k3d cluster with ctlptl
        run: |
          task cluster:create

      - name: Running Test e2e
        run: |
          task test:e2e
