name: E2E Tests

on:
  push:
    paths-ignore:
      - "**.md"
      - "**/*.md"
      - "docs/**"
  pull_request:
    paths-ignore:
      - "**.md"
      - "**/*.md"
      - "docs/**"

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install go-task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Install k3d
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

      - name: Install ctlptl
        run: |
          cd $(mktemp -d)
          curl -fsSL https://github.com/tilt-dev/ctlptl/releases/latest/download/ctlptl.linux.x86_64.tar.gz | tar -xzv
          chmod +x ctlptl
          sudo mv ctlptl /usr/local/bin/ctlptl

      - name: Verify k3d and ctlptl installation
        run: |
          k3d version
          ctlptl version

      - name: Create k3d cluster with ctlptl
        run: |
          task create-cluster

      - name: Running Test e2e
        run: |
          go mod tidy
          task test-e2e
